apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-server
  selector:
    app: redis
    role: master  
